# Generated by Django 3.2.20 on 2023-11-17 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('billing_address', models.TextField(max_length=200)),
                ('shipping_address', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Dispatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_agency', models.CharField(max_length=150)),
                ('order_dispached_date', models.DateTimeField(auto_now_add=True)),
                ('dispatch_manager', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Order Dispatched', 'Order Dispatched')], default='Order Confirmed', max_length=30)),
            ],
            options={
                'db_table': 'order_dispatched_master',
            },
        ),
        migrations.CreateModel(
            name='Order_Placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Received', 'Order Received')], default='Pending', max_length=30)),
                ('order_type', models.CharField(default='buy_now', max_length=10)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.customeraddress')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('basic_price', models.FloatField()),
                ('transportation_charges', models.FloatField()),
                ('additional_taxes', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='oms/images')),
                ('order_received_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Confirmed', 'Order Confirmed')], default='Order Received', max_length=30)),
                ('order_placed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.order_placed')),
            ],
            options={
                'db_table': 'order_received_master',
            },
        ),
        migrations.CreateModel(
            name='Supplier_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=300)),
                ('supplier_contact', models.BigIntegerField()),
                ('supplier_address', models.TextField(max_length=200)),
                ('supplier_gst_no', models.CharField(max_length=20)),
                ('available_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=30)),
            ],
            options={
                'db_table': 'supplier_detail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('basic_price', models.FloatField()),
                ('transportation_charges', models.FloatField()),
                ('additional_taxes', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='oms/images')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.supplier_detail')),
            ],
            options={
                'db_table': 'product_master',
            },
        ),
        migrations.CreateModel(
            name='Order_Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_location', models.CharField(max_length=150)),
                ('order_transit_date', models.DateTimeField(auto_now_add=True)),
                ('transit_vehical', models.CharField(max_length=80)),
                ('transit_vehical_driver', models.CharField(max_length=200)),
                ('driver_contact', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Order Dispatched', 'Order Dispatched'), ('Order Transit', 'Order Transit')], default='Order Dispatched', max_length=30)),
                ('dispatch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.order_dispatched')),
                ('received_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.order_received')),
            ],
            options={
                'db_table': 'order_transit_master',
            },
        ),
        migrations.AddField(
            model_name='order_received',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.product'),
        ),
        migrations.AddField(
            model_name='order_placed',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.product'),
        ),
        migrations.AddField(
            model_name='order_placed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_dispatched',
            name='received_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.order_received'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cancel_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=0)),
                ('product_name', models.CharField(default='Unknown', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('basic_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='products/')),
                ('status', models.CharField(default='Cancelled', max_length=20)),
                ('cancel_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_placed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.order_placed')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.product')),
            ],
            options={
                'db_table': 'cancel_order',
            },
        ),
    ]
